[package]
name = "deresearcher-program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.9"

[features]
no-entrypoint = []

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
